### ISSUE TITLE
TextChoices models

### ISSUE THREAD

**Issue by NikMatyukhin** [perfectrider/wallets#12]
https://docs.djangoproject.com/en/4.1/ref/models/fields/#enumeration-types

в файле `wallets/models.py` используется простое объявление перечисляемых значений. при этом, они используются вне модели (на уровне views есть проверка по типу карты и по типу валюты). всё это стоит перенести на `models.TextChoices` и сравнения делать соответствующим образом, вместо:
`currency == 'RUB'`
сделать:
`currency == CurrencyChoices.RUB`

**Comment by perfectrider** [comment]
Done
